services:
  - type: web
    name: transport-app-backend
    env: node
    plan: free
    rootDir: backend/backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
